// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEvz4ScIX7fAMDijl4bLkQWo2HYaWUP-A',
    appId: '1:713839407956:web:6d6002491ba3b06d74cec1',
    messagingSenderId: '713839407956',
    projectId: 'flutter-529b8',
    authDomain: 'flutter-529b8.firebaseapp.com',
    databaseURL: 'https://flutter-529b8-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-529b8.appspot.com',
    measurementId: 'G-WPYRHKLML4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAt1vNkWgk0X-uCE6duLwJw2IISGf1t01U',
    appId: '1:713839407956:android:156aa3f4ff2317b574cec1',
    messagingSenderId: '713839407956',
    projectId: 'flutter-529b8',
    databaseURL: 'https://flutter-529b8-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-529b8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiDW--UD1D0imsVi_wy9Ona-tz1bc4Jh8',
    appId: '1:713839407956:ios:1288dfc03f841dda74cec1',
    messagingSenderId: '713839407956',
    projectId: 'flutter-529b8',
    databaseURL: 'https://flutter-529b8-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-529b8.appspot.com',
    iosClientId: '713839407956-sp8aajvinohdheqj3v4mcm5gs4pduvvt.apps.googleusercontent.com',
    iosBundleId: 'com.example.admin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiDW--UD1D0imsVi_wy9Ona-tz1bc4Jh8',
    appId: '1:713839407956:ios:318749fcbdbbdcf474cec1',
    messagingSenderId: '713839407956',
    projectId: 'flutter-529b8',
    databaseURL: 'https://flutter-529b8-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-529b8.appspot.com',
    iosClientId: '713839407956-6svsbcfdldfs848p6ves8vg58g5jh41q.apps.googleusercontent.com',
    iosBundleId: 'com.example.admin.RunnerTests',
  );
}
